# Generated by Django 5.1.7 on 2025-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
