# Generated by Django 5.1.7 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.branch'),
        ),
    ]
