# Generated by Django 5.1.7 on 2025-03-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_schedule_studentpaymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpaymenthistory',
            name='remaining',
        ),
    ]
