# Generated by Django 5.1.7 on 2025-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='updated_at',
            new_name='start',
        ),
    ]
