# Generated by Django 5.1.7 on 2025-03-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studentpaymenthistory_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypayment',
            name='remaining_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
