# Generated by Django 5.1.7 on 2025-03-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_at_group_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='start',
            field=models.TimeField(),
        ),
    ]
