# Generated by Django 5.1.7 on 2025-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dailypayment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
