# Generated by Django 5.1.7 on 2025-03-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_end_alter_group_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('archive', 'Archive'), ('activ', 'Activ')], default='activ', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('archive', 'Archive'), ('activ', 'Activ')], default='activ', max_length=15),
        ),
        migrations.AddField(
            model_name='group',
            name='sciences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.sciences'),
            preserve_default=False,
        ),
    ]
