# Generated by Django 5.1.7 on 2025-04-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sciences_group_status_group_sciences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
