# Generated by Django 5.1.7 on 2025-03-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='teacher',
        ),
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
