# Generated by Django 5.1.7 on 2025-03-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_group_created_at_alter_group_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
    ]
