# Generated by Django 5.1.7 on 2025-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bnswer_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='cnswer_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='dnswer_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
