# Generated by Django 5.1.7 on 2025-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_answer_bnswer_text_answer_cnswer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bis_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='cis_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='dis_correct',
            field=models.BooleanField(default=False),
        ),
    ]
