# Generated by Django 5.1.7 on 2025-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_answer_bis_correct_answer_cis_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
