# Generated by Django 5.1.7 on 2025-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_answer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtenanswer',
            name='student_name',
        ),
        migrations.AddField(
            model_name='writtenanswer',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
